package api

import (
	"encoding/json"
	"net"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"

	"github.com/rainmanjam/polyemesis/internal/alerts"
	"github.com/rainmanjam/polyemesis/internal/config"
	"github.com/rainmanjam/polyemesis/internal/db"
)

// plantedSecret is the string that must never reach a chat channel. It is
// shaped like a real stream key on purpose: a test that plants "SECRET" proves
// nothing about a redactor that matches on syntax.
const plantedSecret = "live_9999_PLANTEDSTREAMKEY"

// everyAuditEvent is one of each, built through the same constructors the
// handlers call, with a planted secret in every field a caller can influence.
//
// The token name is the only genuinely free text an audit event carries -- the
// operator types it into a dialog -- and the addresses are attacker-supplied
// whenever the operator has declared a proxy in front of us, because ClientIP
// then reads X-Forwarded-For. Both are treated as hostile here.
func everyAuditEvent() []alerts.Event {
	dirty := "rtmps://live.twitch.tv/app/" + plantedSecret
	return []alerts.Event{
		auditLoginFailed(dirty, 7),
		auditLoginSucceeded(dirty, 7),
		auditPasswordChanged(dirty),
		// The scope is NOT planted, and the asymmetry is the point: the name is
		// free text an operator types, while the scope is validated against a
		// closed set before it is ever stored, so a hostile value cannot reach
		// this field without db.ValidScope having already refused it.
		auditAPITokenCreated("deploy bot streamkey="+plantedSecret, db.ScopeAdmin, dirty),
		auditAPITokenRevoked("deploy bot streamkey="+plantedSecret, dirty),
		auditSettingsChanged([]string{"ingest", "listeners"}, dirty),
		// A realistic clip name rather than a planted one, and the distinction
		// is load-bearing. clips.Clip.Name is generated by the server from a
		// timestamp, so no operator-supplied string reaches this field -- that
		// is a STRUCTURAL guarantee, not a redaction one. alerts.Redact matches
		// syntax, so a bare scalar goes through it untouched (planting one here
		// fails this test, which is how that was established). Anything that
		// ever makes this name caller-supplied must sanitise it at the source;
		// the redactor will not.
		auditClipCaptured("clip-20260806-143000.ts", dirty),
		// A realistic release tag rather than a planted one, for exactly the
		// reason auditClipCaptured spells out above: the version is read from
		// this server's own update feed and never from operator text, which is
		// a STRUCTURAL guarantee. alerts.Redact matches syntax, so a bare
		// scalar goes through it untouched -- planting one here fails this
		// test, which is how that was re-established. Anything that ever lets
		// a caller name the version to install must sanitise at the source.
		auditUpgradeStaged("v1.2.3", true, dirty),
		auditUpgradeRolledBack(true, dirty),
	}
}

// everyAuditEvent must actually be every one of them.
//
// The redaction test iterates this list, so a constructor added without a line
// here is a constructor whose output nothing checks before it reaches a chat
// channel -- silently, and in exactly the class of change most likely to add
// one.
func TestEveryAuditEventIsCoveredByTheRedactionTest(t *testing.T) {
	seen := map[alerts.Type]bool{}
	for _, ev := range everyAuditEvent() {
		seen[ev.Type] = true
	}
	for _, ty := range alerts.AllTypes() {
		switch ty {
		// The operational types are raised by the engine's watcher, not by this
		// package, so there is no constructor here to check. Their fields come
		// from measurements rather than from anything an operator typed, which
		// is the property that makes them uninteresting to a leak test -- and
		// it is a property worth re-checking before adding to this list.
		case alerts.TypeDestinationDown, alerts.TypeDestinationRecovered,
			alerts.TypeDestinationFallingBehind, alerts.TypeDestinationCaughtUp,
			alerts.TypeIngestLost, alerts.TypeIngestRecovered,
			alerts.TypeFailoverSwitched, alerts.TypeClipping,
			alerts.TypeDiskLow, alerts.TypeDiskRecovered,
			alerts.TypeLoudnessOut, alerts.TypeLoudnessRecovered:
			continue
		// broadcast.fault is OPERATIONAL and is raised by this package, which is
		// a combination none of the above covers -- so it is exempted here for
		// its own reason rather than folded into theirs. It cannot join
		// everyAuditEvent because the two invariants that list enforces are
		// properties of AUDIT events specifically: an audit event must set no
		// coalescing Key (see the flood argument below), while an operational
		// one must, or a destination refusing every fifteen seconds becomes two
		// hundred and forty messages an hour.
		//
		// It is not left unchecked. TestABroadcastFaultAlertNeverCarriesASecret
		// in lifecycle_test.go plants the same secret in the one field of it
		// that is not written by this process -- the platform's own error text
		// -- and asserts the same three encodings.
		case alerts.TypeBroadcastFault:
			continue
		}
		if !seen[ty] {
			t.Errorf("%s is subscribable but has no entry in everyAuditEvent, so nothing checks it for leaks", ty)
		}
	}
}

// The most important test in this file, and the reason the constructors live in
// one place rather than at five call sites.
//
// The destination of these events is a chat channel that outlives the incident
// and gets screenshotted into tickets. Notifier.Publish applies Redacted on the
// way in, so this asserts the same composition the delivery path performs --
// construct, redact, encode -- against all three wire formats, because a field
// that survives redaction still has to survive the Discord and Slack encoders
// putting it somewhere.
//
// Mutation: give auditAPITokenCreated a field carrying the name verbatim past
// WithField, e.g. by writing the name into Event.Text after the redactor has
// run. There is no such hole today; the test exists so that adding one fails
// here rather than in somebody's Slack.
// A forged X-Forwarded-For must never reach a payload.
//
// POST /api/v1/auth/login is unauthenticated, so with trustProxyHeaders on
// anyone who can reach it controls what auth.ClientIP returns -- that function
// takes the leftmost segment after a TrimSpace and validates nothing, which is
// correct for the throttle (the value is only ever a map key there) and wrong
// the moment the same string is rendered into an operator's channel.
//
// Redaction cannot cover this. alerts.Redact matches syntax, so ordinary prose
// carrying a link goes through it unchanged; the payload assertions below are
// deliberately about the whole rendered body rather than about the field.
func TestAForgedForwardedForCannotReachAPayload(t *testing.T) {
	const forged = "not-an-ip <@channel> visit https://evil.example/ now"

	for _, tc := range []struct {
		name       string
		trustProxy bool
		header     string
		want       string
	}{
		{"forged header, proxy trusted", true, forged, "203.0.113.9"},
		{"forged header, proxy not trusted", false, forged, "203.0.113.9"},
		{"real address, proxy trusted", true, "198.51.100.4", "198.51.100.4"},
		{"no header at all", true, "", "203.0.113.9"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			s, _, _ := testServer(t, config.Config{TrustProxyHeaders: tc.trustProxy})
			r := httptest.NewRequest(http.MethodPost, "/api/v1/auth/login", nil)
			r.RemoteAddr = "203.0.113.9:51234"
			if tc.header != "" {
				r.Header.Set("X-Forwarded-For", tc.header)
			}

			got := s.clientIP(r)
			if got != tc.want {
				t.Errorf("clientIP = %q, want %q", got, tc.want)
			}
			if net.ParseIP(got) == nil {
				t.Errorf("clientIP returned %q, which is not an address", got)
			}

			// The end-to-end assertion: nothing an attacker wrote survives as
			// far as a delivered message, in any format.
			ev := auditLoginFailed(got, 3)
			for _, format := range []alerts.Format{alerts.FormatJSON, alerts.FormatDiscord, alerts.FormatSlack} {
				rule := alerts.Rule{ID: 1, Name: "ops", Enabled: true, URL: "https://example.test/hook", Format: format}
				body, _, err := alerts.Encode(alerts.Delivery{
					Rule:  rule.Normalized(),
					Items: []alerts.Item{{Event: ev.Redacted(), Count: 1}},
				})
				if err != nil {
					t.Fatalf("Encode(%s): %v", format, err)
				}
				for _, fragment := range []string{"evil.example", "@channel", "not-an-ip"} {
					if strings.Contains(string(body), fragment) {
						t.Errorf("%s payload leaked %q:\n%s", format, fragment, body)
					}
				}
			}
		})
	}
}

func TestNoAuditEventCarriesASecretToTheWire(t *testing.T) {
	rule := alerts.Rule{ID: 1, Name: "ops", Enabled: true, URL: "https://example.test/hook"}
	for _, format := range []alerts.Format{alerts.FormatJSON, alerts.FormatDiscord, alerts.FormatSlack} {
		for _, ev := range everyAuditEvent() {
			t.Run(string(format)+"/"+string(ev.Type), func(t *testing.T) {
				r := rule
				r.Format = format
				body, _, err := alerts.Encode(alerts.Delivery{
					Rule:  r.Normalized(),
					Items: []alerts.Item{{Event: ev.Redacted(), Count: 1}},
				})
				if err != nil {
					t.Fatalf("Encode: %v", err)
				}
				if strings.Contains(string(body), plantedSecret) {
					t.Fatalf("a %s audit event carried a secret to the wire:\n%s", ev.Type, body)
				}
				if !strings.Contains(string(body), alerts.Mask) {
					t.Errorf("a %s audit event dropped the text entirely instead of masking it; "+
						"the operator still needs to know something happened:\n%s", ev.Type, body)
				}
			})
		}
	}
}

// The flood invariant, as a one-line assertion rather than a code review.
//
// Publish defaults an empty Key to the type name, which gives every audit event
// of one type a single coalescing subject for the whole install. A key per
// source address would instead create one pending group per attacking address,
// and coalescer.evictIfFull drops a RULE's oldest pending group once that rule
// holds maxGroupsPerRule -- scanning every group belonging to it regardless of
// event type. A distributed guesser would therefore evict the destination.down
// sitting in its debounce window. Operational alerting has to survive security
// alerting.
//
// Mutation: set Key to the address in auditLoginFailed. Observed FAIL.
func TestAuditEventsNeverSetTheirOwnCoalescingKey(t *testing.T) {
	for _, ev := range everyAuditEvent() {
		if ev.Key != "" {
			t.Errorf("%s set Key = %q; one address per group is how a brute force "+
				"evicts an operational alert", ev.Type, ev.Key)
		}
	}
}

// Severity is the operator's existing off switch, so it is part of the contract
// rather than an implementation detail: a rule raised to critical-only is
// somebody's phone, and what does and does not reach it is decided here.
func TestAuditSeveritiesMatchWhatTheFloorsPromise(t *testing.T) {
	want := map[alerts.Type]alerts.Severity{
		alerts.TypePasswordChanged: alerts.SeverityCritical,
		alerts.TypeAPITokenCreated: alerts.SeverityCritical,
		alerts.TypeLoginFailed:     alerts.SeverityWarning,
		alerts.TypeSettingsChanged: alerts.SeverityWarning,
		// Revocation is warning, not critical: minting hands out a credential
		// that acts as the admin and never expires, while revoking takes one
		// away. The dangerous direction is the one that creates access.
		alerts.TypeAPITokenRevoked: alerts.SeverityWarning,
		alerts.TypeLoginSucceeded:  alerts.SeverityInfo,
		// Info, and the quietest here on purpose: on a busy stream this fires
		// repeatedly and is somebody doing their job. A rule that wants only
		// incidents drops it with MinSeverity rather than unsubscribing.
		alerts.TypeClipCaptured: alerts.SeverityInfo,
		// Critical, on exactly auditAPITokenCreated's reasoning: what these
		// record survives the response to a compromise. A replaced binary
		// outlives a password change, a token revocation AND a restart, and
		// the restart is what arms it. A rollback is the same act in the
		// other direction.
		alerts.TypeUpgradeStaged:     alerts.SeverityCritical,
		alerts.TypeUpgradeRolledBack: alerts.SeverityCritical,
	}
	seen := map[alerts.Type]bool{}
	for _, ev := range everyAuditEvent() {
		seen[ev.Type] = true
		if got := ev.Severity; got != want[ev.Type] {
			t.Errorf("%s severity = %q, want %q", ev.Type, got, want[ev.Type])
		}
		if ev.Title == "" {
			t.Errorf("%s has no title; Slack and Discord both render it as the heading", ev.Type)
		}
	}
	for ty := range want {
		if !seen[ty] {
			t.Errorf("no constructor produced %s", ty)
		}
	}
}

// A NAME travels and a VALUE never does, asserted against a settings document
// whose every interesting string is the planted secret.
//
// alerts.Redact cannot save us here and that is the whole point: it is a syntax
// matcher, so Redact("hunter2") returns "hunter2" unchanged. A bare SRT
// passphrase would go to the channel verbatim. The only defence is that a value
// is never put in the event to begin with, which is what this pins.
//
// Mutation: have changedSections return "ingest=" + string(the section's JSON)
// instead of the bare key. Observed FAIL.
func TestSettingsChangedNamesSectionsAndNeverValues(t *testing.T) {
	before := db.DefaultSettings()
	after := before
	after.Ingest.SRT.Passphrase = plantedSecret
	after.Ingest.RTMP.StreamKey = plantedSecret
	after.Listeners.SRTPort = before.Listeners.SRTPort + 1

	names := changedSections(mustJSON(t, before), mustJSON(t, after))
	if !reflect.DeepEqual(names, []string{"ingest", "listeners"}) {
		t.Fatalf("changedSections = %v, want [ingest listeners]", names)
	}
	// Every name returned is a top-level key of the settings document. This is
	// the property that makes the event safe by construction rather than by
	// review: a section name is drawn from a fixed vocabulary the operator's
	// data cannot enter.
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(mustJSON(t, after), &doc); err != nil {
		t.Fatalf("unmarshal settings: %v", err)
	}
	for _, name := range names {
		if _, ok := doc[name]; !ok {
			t.Errorf("changedSections returned %q, which is not a settings section", name)
		}
	}

	ev := auditSettingsChanged(names, "10.0.0.9")
	blob := mustJSON(t, ev)
	if strings.Contains(string(blob), plantedSecret) {
		t.Fatalf("the settings.changed event carried a stored value:\n%s", blob)
	}
}

// A save that stored the identical document is not an event.
//
// Somebody opening the settings page and pressing Save without touching
// anything is the single most common way to reach this handler, and an alert
// for it is the noise that gets the whole channel muted. It also has to notice
// a change anywhere in the document, not just in the sections somebody thought
// of, so the sweep is over the marshalled JSON rather than a hand-written list.
func TestChangedSectionsIsSilentWhenNothingMoved(t *testing.T) {
	s := db.DefaultSettings()
	if names := changedSections(mustJSON(t, s), mustJSON(t, s)); len(names) != 0 {
		t.Fatalf("changedSections on an unchanged document = %v, want none", names)
	}

	// Every top-level section, one at a time, so a section that stops being
	// compared shows up here rather than as an alert that silently stopped
	// firing. The mutation is applied through the JSON rather than through Go
	// fields, which is what lets this cover sections nobody has thought about
	// since.
	var doc map[string]json.RawMessage
	if err := json.Unmarshal(mustJSON(t, s), &doc); err != nil {
		t.Fatalf("unmarshal settings: %v", err)
	}
	for section := range doc {
		t.Run(section, func(t *testing.T) {
			mutated := map[string]json.RawMessage{}
			for k, v := range doc {
				mutated[k] = v
			}
			mutated[section] = json.RawMessage(`{"polyemesisTestMarker":true}`)
			after, err := json.Marshal(mutated)
			if err != nil {
				t.Fatalf("marshal mutated settings: %v", err)
			}
			names := changedSections(mustJSON(t, s), after)
			if !reflect.DeepEqual(names, []string{section}) {
				t.Fatalf("changedSections = %v, want [%s]", names, section)
			}
		})
	}
}

// publishAudit is called from POST /api/v1/auth/login, which every test in this
// package reaches with a nil manager -- testServer says so in as many words.
// Manager.Default takes a read lock on the manager, so an unguarded call turns
// signing in into a panic under `go test ./internal/api`.
//
// The guard is reachable on a real install too: Manager.reconcile logs and
// continues when engine.New fails, so an install whose video pipeline will not
// build has no default engine. A login endpoint that panics because of that is
// a far worse outage than the one it would have been reporting.
func TestPublishAuditIsANoOpWithoutAnEngine(t *testing.T) {
	s, h, _ := testServer(t, config.Config{})
	if s.mgr != nil {
		t.Fatal("this test is only meaningful with a nil manager; testServer changed")
	}
	for _, ev := range everyAuditEvent() {
		s.publishAudit(ev)
	}

	// And through the handler, because the guard has to hold on the path that
	// actually calls it. A wrong password is the branch that publishes.
	w := do(t, h, jsonRequest(t, "POST", "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "not the password"}))
	if w.Code != 401 {
		t.Fatalf("login with a wrong password = %d, want 401", w.Code)
	}
	w = do(t, h, jsonRequest(t, "POST", "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": testPassword}))
	if w.Code != 200 {
		t.Fatalf("login with the right password = %d, want 200: %s", w.Code, w.Body)
	}
}

// The throttled branch publishes nothing.
//
// A 429 is answered before the body is read and long before bcrypt runs, so
// publishing there would hand an attacker the event rate: one alert per
// request, at whatever speed they can open sockets, against a rule whose
// debounce is the only thing between that and the operator's phone. The
// failures that matter have already been reported by the branch below.
func TestTheThrottledLoginBranchRaisesNothing(t *testing.T) {
	s, _, _ := testServer(t, config.Config{})
	got := captureAudit(t, s)
	for i := 0; i < 20; i++ {
		s.logins.Fail("192.0.2.7")
	}
	r := jsonRequest(t, "POST", "/api/v1/auth/login",
		map[string]string{"username": "admin", "password": "guess"})
	r.RemoteAddr = "192.0.2.7:5555"
	w := httptest.NewRecorder()
	s.Handler().ServeHTTP(w, r)
	if w.Code != 429 {
		t.Fatalf("a throttled login = %d, want 429", w.Code)
	}
	// The counter did not move, which is what "the attacker cannot set the
	// event rate" means concretely: the request cost them a socket and cost the
	// operator nothing.
	if n := s.logins.Failures("192.0.2.7"); n != 20 {
		t.Fatalf("a throttled request changed the failure count to %d, want 20", n)
	}
	// And, the part the counter cannot show: no event was raised. Asserting only
	// the counter let a publish be added to the 429 branch without failing --
	// the mutation was tried and the test stayed green.
	if len(*got) != 0 {
		t.Fatalf("the throttled branch raised %d event(s): %v", len(*got), *got)
	}
}

// captureAudit diverts audit events into a slice for the life of the test.
//
// Without this the handlers' publishes are unobservable here -- publishAudit
// needs a manager and a started engine, and testServer provides neither -- so
// every assertion in this file could only reach the constructors. See the
// auditSink field on Server.
func captureAudit(t *testing.T, s *Server) *[]alerts.Event {
	t.Helper()
	var got []alerts.Event
	s.auditSink = func(ev alerts.Event) { got = append(got, ev) }
	t.Cleanup(func() { s.auditSink = nil })
	return &got
}

func typesOf(evs []alerts.Event) []string {
	out := make([]string, 0, len(evs))
	for _, e := range evs {
		out = append(out, string(e.Type))
	}
	return out
}

// The handlers are wired to the right events on the right branches.
//
// This is the gap that let all five publishAudit call sites be deleted with the
// package still passing: everything else in this file exercises constructors in
// isolation, which says nothing about whether a handler ever calls one.
func TestTheLoginHandlerRaisesTheRightEventOnEachBranch(t *testing.T) {
	t.Run("a wrong password inside the free allowance stays quiet", func(t *testing.T) {
		s, h, _ := testServer(t, config.Config{})
		got := captureAudit(t, s)
		r := jsonRequest(t, "POST", "/api/v1/auth/login",
			map[string]string{"username": "admin", "password": "wrong"})
		r.RemoteAddr = "198.51.100.20:4444"
		if w := do(t, h, r); w.Code != 401 {
			t.Fatalf("= %d, want 401", w.Code)
		}
		// The allowance is what keeps a fat-fingered password out of the
		// operator's channel. If this ever fires on the first miss, the feature
		// becomes the thing people mute.
		if len(*got) != 0 {
			t.Fatalf("a first wrong password raised %v", typesOf(*got))
		}
	})

	t.Run("the attempt that exhausts the allowance raises auth.login.failed", func(t *testing.T) {
		s, h, _ := testServer(t, config.Config{})
		const ip = "198.51.100.21"
		got := captureAudit(t, s)

		// Driven through the handler rather than by seeding the throttle, and
		// looped rather than hard-coding the allowance: the publishing request
		// is the one where Fail first returns a penalty, and every request after
		// that is answered 429 before the password is even read. Hard-coding the
		// count here would make this test a restatement of the throttle's
		// constant instead of a check on the wiring.
		var status int
		for i := 0; i < 30 && len(*got) == 0; i++ {
			r := jsonRequest(t, "POST", "/api/v1/auth/login",
				map[string]string{"username": "admin", "password": "wrong"})
			r.RemoteAddr = ip + ":4444"
			status = do(t, h, r).Code
			if status == 429 {
				break
			}
		}
		if len(*got) == 0 {
			t.Fatalf("no event was raised before the address was throttled (last status %d)", status)
		}
		if len(*got) != 1 {
			t.Errorf("raised %d events, want 1: %v", len(*got), typesOf(*got))
		}
		if (*got)[0].Type != alerts.TypeLoginFailed {
			t.Errorf("raised %s, want %s", (*got)[0].Type, alerts.TypeLoginFailed)
		}
	})

	t.Run("the right password raises auth.login.succeeded", func(t *testing.T) {
		s, h, _ := testServer(t, config.Config{})
		got := captureAudit(t, s)
		r := jsonRequest(t, "POST", "/api/v1/auth/login",
			map[string]string{"username": "admin", "password": testPassword})
		r.RemoteAddr = "198.51.100.22:4444"
		if w := do(t, h, r); w.Code != 200 {
			t.Fatalf("= %d, want 200: %s", w.Code, w.Body)
		}
		if want := []string{string(alerts.TypeLoginSucceeded)}; !reflect.DeepEqual(typesOf(*got), want) {
			t.Fatalf("raised %v, want %v", typesOf(*got), want)
		}
	})
}

func mustJSON(t *testing.T, v any) []byte {
	t.Helper()
	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	return b
}
