package api

import (
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// THE LEDGER'S OWN REGENERATION COMMAND HAD ALREADY DECAYED.
//
// #173 documented, in three places -- route_ledger_test.go twice and the first
// line of testdata/route-coverage.json -- that the artifact is regenerated by
// `go test ./internal/api` with `-update-coverage` and a -run filter naming
// TestRouteCoverageLedger. (Written here in pieces rather than as a command a
// reader could copy: this file is inside the corpus the scanner below reads,
// and a doc comment that publishes a working-looking command for a test that
// does not exist is the defect itself. The widened scan found this line.)
//
// There is no TestRouteCoverageLedger. It was renamed to TestLedgerPreflight
// and the three strings were not. Running the documented command prints
//
//	ok  github.com/rainmanjam/polyemesis/internal/api  0.735s [no tests to run]
//
// which is the failure this whole ledger exists to catch, committed inside the
// file written to catch it: a green tick from a run that executed nothing. A
// maintainer following the instruction gets a pass, no regenerated artifact,
// and no indication that the two are related.
//
// It is also the cheapest possible statement of the round's thesis. A hand-
// maintained string was joined to nothing that emits, so nothing failed when
// the thing it named stopped existing. The fix is the same shape as every
// other fix here: derive it, then reconcile the derivation against the
// committed copy.
//
// Two mechanisms, because they catch different halves:
//
//  1. ledgerRegenCommand builds the string from t.Name() at run time, so the
//     command in an error message cannot name a test other than the one
//     printing it. A rename carries automatically.
//  2. This test scans the ledger's source and its artifact for every `-run
//     <Name>` written by hand, and requires each name to match a test function
//     that actually exists in this package -- the test names being derived,
//     independently, from the package's ASTs. Neither set is hand-maintained,
//     and the disagreement between them is the failure.

// ledgerRegenCommand is the ONE place the regeneration command is spelled, and
// it is spelled from the running test's own name.
//
// The subtest suffix is stripped: the preflight runs its counterparts as
// t.Run("counterparts", ...) in strict mode, and an error surfacing from inside
// that subtest must still tell the reader to run the parent.
func ledgerRegenCommand(t *testing.T) string {
	t.Helper()
	return "go test ./internal/api -run '^" + rootTestName(t) + "$' -update-coverage"
}

func rootTestName(t *testing.T) string {
	name := t.Name()
	if i := strings.IndexByte(name, '/'); i >= 0 {
		name = name[:i]
	}
	return name
}

// runFilterMention is a REGENERATION INSTRUCTION: a `-run <TestName>` on the
// same line as `-update-coverage`. It deliberately accepts the quoted anchored
// form this change introduces AND the bare form #173 used, because the point is
// to catch the bare ones that are still lying, not to insist on a spelling.
//
// WHY `-update-coverage` IS PART OF THE PATTERN. The first version of this
// scanner matched any `-run <Name>` and then read a HAND-PICKED TWO FILES --
// route_ledger_test.go and the artifact -- which is this round's own thesis
// (complete over a set that excludes something) inside the fix for it. The
// identical dead string `-run TestSomethingElse` survived untouched in
// main_test.go:13, same package, and this round REWORDED PROSE in the scanned
// file to fit the scanner rather than widening it.
//
// Widening the file set to the whole package makes main_test.go's mention
// visible, and there it is an ILLUSTRATION -- "`go test ./internal/api -run
// TestSomethingElse` ran none of it" is a sentence about arbitrary filters, and
// flagging it would be a false positive. Rewording it to satisfy the guard is
// what the previous round did and is not available twice.
//
// So the guard's subject narrows to what it can actually decide: an instruction
// a reader would COPY in order to regenerate the artifact is one that carries
// -update-coverage. Every file in the package is scanned; the discriminator is
// a property of the text rather than of the filename. The residual is recorded
// in the deferral list: a `-run` naming a dead test in a mention that is not a
// regeneration command still passes, because nothing here can tell an
// illustration from an instruction, and the previous design answered that by
// choosing which files to look at.
var runFilterMention = regexp.MustCompile(`-run\s+'?\^?(Test[A-Za-z0-9_]+)\$?'?[^\n]*-update-coverage`)

// declaredTestNames derives, from the ASTs of this package's test files, every
// name `go test -run` could match. Parsed rather than grepped for the same
// reason the shape deriver in this round is parsed rather than grepped: a
// regexp over source answers a question about text, and the question here is
// about declarations.
func declaredTestNames(t *testing.T) map[string]bool {
	t.Helper()
	names := map[string]bool{}
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("read package dir: %v", err)
	}
	fset := token.NewFileSet()
	files := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, e.Name(), nil, 0)
		if err != nil {
			t.Fatalf("parse %s: %v", e.Name(), err)
		}
		files++
		for _, d := range f.Decls {
			fn, ok := d.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || fn.Name == nil {
				continue
			}
			if strings.HasPrefix(fn.Name.Name, "Test") {
				names[fn.Name.Name] = true
			}
		}
	}
	// A floor, in the same spirit as every other floor here. If the directory
	// walk ever reads zero test files -- a changed working directory, a build
	// tag, a rename of the suffix -- the reconciliation below would find every
	// mention "unmatched"... or, worse, if the assertion were inverted, would
	// find nothing to disagree with and pass. Say so loudly instead.
	if files == 0 || len(names) == 0 {
		t.Fatalf("derived %d test names from %d _test.go files in this package; "+
			"a deriver that finds nothing cannot reconcile anything", len(names), files)
	}
	return names
}

// assertRunFilterRegexStillMatches is this scanner's positive control.
//
// The scan below is an absence check -- "no mention names a dead test" -- and an
// absence check over a pattern that has stopped matching anything passes
// perfectly. That is the seventh vacuous guard in one sentence, so the pattern
// is required to match a known instance of each spelling it must cover before
// any file is read.
//
// Note the asymmetry with the files themselves: ZERO mentions in the source is
// the goal state, not a failure. Once the command is built by
// ledgerRegenCommand(t) there is nothing left to hand-write, so anchoring
// liveness on "the source must mention one" would forbid the fix. The anchor
// lives here, on the regexp, and on the artifact -- which is materialised prose
// and must always carry exactly one.
func assertRunFilterRegexStillMatches(t *testing.T) {
	t.Helper()
	// THE FIXTURES NAME A LIVE TEST ON PURPOSE, and it is not cosmetic. This
	// file is inside the corpus the scan below reads -- that was the whole
	// point of widening it -- so a fixture spelling out a regeneration command
	// for a test that does not exist IS the defect this guard reports, sitting
	// in the guard. The control is over the three SPELLINGS the pattern must
	// cover (bare, quoted-and-anchored, minimal); the name in them is free, so
	// it is the live one.
	for _, c := range []struct{ in, want string }{
		{"go test ./internal/api -run " + ledgerWriterTestName + " -update-coverage", ledgerWriterTestName},
		{"go test ./internal/api -run '^" + ledgerWriterTestName + "$' -update-coverage", ledgerWriterTestName},
		{"-run " + ledgerWriterTestName + " -update-coverage", ledgerWriterTestName},
	} {
		m := runFilterMention.FindStringSubmatch(c.in)
		if m == nil || m[1] != c.want {
			t.Fatalf("runFilterMention no longer matches %q (got %v, want %q). "+
				"Every check below is an absence check; a pattern that matches "+
				"nothing makes all of them pass while reading nothing.", c.in, m, c.want)
		}
	}
	// And the NEGATIVE control, which is what makes the discriminator honest
	// rather than convenient: a bare -run with no -update-coverage is an
	// illustration, not a regeneration instruction, and the scanner must not
	// claim it. If this ever starts matching, main_test.go's sentence about
	// arbitrary -run filters becomes a false failure and somebody reworders
	// prose to fit a guard again.
	if m := runFilterMention.FindStringSubmatch("`go test ./internal/api -run TestSomethingElse` ran none of it"); m != nil {
		t.Fatalf("runFilterMention matched an illustrative -run with no -update-coverage "+
			"(%v). The scan below reads every file in this package; a pattern this wide "+
			"turns the package's own prose about -run filters into failures.", m)
	}
}

func TestEveryDocumentedRunFilterNamesALiveTest(t *testing.T) {
	assertRunFilterRegexStillMatches(t)
	declared := declaredTestNames(t)

	// EVERY Go file in this package, plus the artifact -- derived, not chosen.
	// The previous version read exactly two names, and the file it did not read
	// contained the identical dead string.
	sources := packageGoFiles(t)
	sources = append(sources, coveragePath)
	for _, name := range sources {
		b, err := os.ReadFile(name)
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		seen := map[string]bool{}
		for _, m := range runFilterMention.FindAllStringSubmatch(string(b), -1) {
			seen[m[1]] = true
		}
		// The artifact is generated prose and must always carry the command;
		// the source ideally carries none. Only the former is anchored.
		if name == coveragePath && len(seen) == 0 {
			t.Errorf("%s documents no -run filter at all, so nobody reading it can "+
				"regenerate it -- and the next person to try will edit it by hand, "+
				"which is how a committed ceiling gets raised without a diff anybody "+
				"reads.", name)
		}
		names := make([]string, 0, len(seen))
		for n := range seen {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			if declared[n] {
				continue
			}
			t.Errorf("%s tells a reader to run `-run %s`, and no test of that name "+
				"exists in package api.\n"+
				"`go test ./internal/api -run %s -update-coverage` prints "+
				"\"[no tests to run]\" and exits 0: a green tick from a run that "+
				"executed nothing, and no regenerated artifact. That is the exact "+
				"pathology this ledger was built to catch, committed inside it.\n"+
				"Do not re-hardcode the new name -- use ledgerRegenCommand(t), which "+
				"derives it from t.Name() so the next rename carries.\n"+
				"tests that DO exist and look close: %v",
				filepath.Base(name), n, n, nearestNames(n, declared))
		}
	}
}

// packageGoFiles is every .go file in this package directory, sorted. It has
// its own floor for the same reason declaredTestNames does: a walk that reads
// nothing satisfies an absence check perfectly.
func packageGoFiles(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("read package dir: %v", err)
	}
	var out []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
			out = append(out, e.Name())
		}
	}
	sort.Strings(out)
	if len(out) < 20 {
		t.Fatalf("found %d .go files in package api; that is not this package, and a "+
			"scan of nothing cannot find a dead -run filter", len(out))
	}
	return out
}

// nearestNames is a diagnostic, not an assertion: when a filter names a test
// that has been renamed, the renamed one is usually recognisable.
func nearestNames(want string, declared map[string]bool) []string {
	var out []string
	for n := range declared {
		if strings.Contains(n, "Ledger") || strings.Contains(n, "Coverage") {
			out = append(out, n)
		}
	}
	sort.Strings(out)
	if len(out) > 6 {
		out = out[:6]
	}
	return out
}

// TestTheDocumentedRegenerationCommandActuallyRegenerates closes the other
// half. The test above proves the NAME resolves; this proves the name resolves
// to the test that owns the write. A `-run` naming some other live test would
// satisfy the first check and still regenerate nothing.
func TestTheDocumentedRegenerationCommandActuallyRegenerates(t *testing.T) {
	b, err := os.ReadFile(coveragePath)
	if err != nil {
		t.Fatalf("read %s: %v", coveragePath, err)
	}
	m := runFilterMention.FindStringSubmatch(string(b))
	if m == nil {
		t.Fatalf("%s documents no regeneration command; a reader has no way to "+
			"regenerate it and no way to know that is why their edit keeps "+
			"reverting", coveragePath)
	}
	documented := m[1]

	// ledgerWriterTestName is asserted, not derived from the same string, so
	// this is a reconciliation and not a tautology: the constant below is
	// itself checked against the live test set by the test above.
	if documented != ledgerWriterTestName {
		t.Errorf("%s documents `-run %s`, but the test that calls writeLedger is %s. "+
			"Running the documented command would execute a different test -- or "+
			"none -- and regenerate nothing, while exiting 0.",
			coveragePath, documented, ledgerWriterTestName)
	}
	if !declaredTestNames(t)[ledgerWriterTestName] {
		t.Errorf("ledgerWriterTestName is %q and no such test is declared in this "+
			"package", ledgerWriterTestName)
	}
}

// ledgerWriterTestName names the test that owns writeLedger. It is a constant
// rather than a t.Name() because it has to be readable from a DIFFERENT test,
// and it is kept honest by TestTheDocumentedRegenerationCommandActuallyRegenerates
// above plus the compile-time reference in TestLedgerPreflight itself.
const ledgerWriterTestName = "TestLedgerPreflight"
