import { useEffect, useRef, useState } from "react";
import Hls from "hls.js";
import { MonitorPlay, VolumeX, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/** Low-latency HLS preview of the relay.
 *
 *  The stream is generated by a dedicated FFmpeg process reading its own relay
 *  subscription, so nothing here can affect a destination. The player retries
 *  quietly: before the encoder connects there is simply no playlist, and that
 *  is a normal state, not an error worth shouting about. */
export function PreviewPlayer({
  active,
  className,
}: {
  active: boolean;
  className?: string;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(true);

  useEffect(() => {
    const video = videoRef.current;
    if (!video || !active) return;

    const src = "/hls/index.m3u8";
    let hls: Hls | null = null;
    let retry: number | undefined;

    const start = () => {
      if (Hls.isSupported()) {
        hls = new Hls({
          // Tuned for a monitor feed: stay near the live edge and prefer
          // skipping to catching up smoothly.
          lowLatencyMode: true,
          // Load-bearing, and it was missing. hls.js gates its whole
          // catch-up controller on
          //   !lowLatencyMode || maxLiveSyncPlaybackRate === 1
          // and maxLiveSyncPlaybackRate DEFAULTS TO 1 (verified in the
          // installed 1.6.16 build), so lowLatencyMode alone returned early
          // every time and the player never nudged itself back toward the
          // edge. 1.08 is fast enough to recover a second of drift within a
          // few seconds and slow enough that nobody hears the pitch shift.
          maxLiveSyncPlaybackRate: 1.08,
          // Target latency is liveSyncDurationCount x EXT-X-TARGETDURATION.
          // At the 1s segments the server now emits, that is 2s.
          liveSyncDurationCount: 2,
          liveMaxLatencyDurationCount: 6,
          maxBufferLength: 6,
          manifestLoadingMaxRetry: 0,
          levelLoadingMaxRetry: 2,
        });
        hls.loadSource(src);
        hls.attachMedia(video);
        hls.on(Hls.Events.MANIFEST_PARSED, () => {
          void video.play().then(() => setPlaying(true)).catch(() => setPlaying(false));
        });
        hls.on(Hls.Events.ERROR, (_e, data) => {
          if (!data.fatal) return;
          setPlaying(false);
          hls?.destroy();
          hls = null;
          // No playlist yet just means nobody is streaming. Keep looking.
          retry = window.setTimeout(start, 4000);
        });
      } else if (video.canPlayType("application/vnd.apple.mpegurl")) {
        // Safari plays HLS natively and does not need (or want) hls.js.
        video.src = src;
        void video.play().then(() => setPlaying(true)).catch(() => setPlaying(false));
      }
    };

    start();
    return () => {
      if (retry) window.clearTimeout(retry);
      hls?.destroy();
    };
  }, [active]);

  return (
    <div
      className={cn(
        "relative aspect-video w-full overflow-hidden rounded-md border border-border bg-black",
        className,
      )}
    >
      <video
        ref={videoRef}
        className="h-full w-full object-contain"
        muted={muted}
        playsInline
        controls={false}
      />

      {!playing && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-muted-foreground">
          <MonitorPlay className="h-6 w-6 opacity-40" />
          <span className="text-[11px]">
            {active ? "Waiting for a stream…" : "Preview is disabled in Settings"}
          </span>
        </div>
      )}

      {playing && (
        <div className="absolute bottom-2 right-2 flex items-center gap-1">
          <Button
            variant="secondary"
            size="icon-sm"
            onClick={() => setMuted((m) => !m)}
            aria-label={muted ? "Unmute preview" : "Mute preview"}
          >
            {muted ? <VolumeX /> : <Volume2 />}
          </Button>
        </div>
      )}
    </div>
  );
}
