import { useEffect, useRef, useState } from "react";
import Hls from "hls.js";
import { MonitorPlay, VolumeX, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/** Low-latency HLS preview of the relay.
 *
 *  The stream is generated by a dedicated FFmpeg process reading its own relay
 *  subscription, so nothing here can affect a destination. The player retries
 *  quietly: before the encoder connects there is simply no playlist, and that
 *  is a normal state, not an error worth shouting about. */
export function PreviewPlayer({
  active,
  className,
  sourceId,
  outputLive,
  ingestLive,
  onAir,
  aspect,
}: {
  active: boolean;
  className?: string;
  /** Which programme to show. Omitted means the default source's alias. */
  sourceId?: number;
  /** Anything reaching this programme's destinations -- encoder, backup, slate
   *  or playlist. Decides whether a picture is worth showing at all. */
  outputLive?: boolean;
  /** The operator's own encoder arriving. LABELS the picture; it must not hide
   *  it, because with the slate on air this is false while something real is
   *  being broadcast. */
  ingestLive?: boolean;
  /** The tier on air: "primary", "backup", "slate", "playlist". */
  onAir?: string;
  /** The source's measured geometry, so a vertical or 4:3 programme is not
   *  letterboxed into a 16:9 box it never filled. */
  aspect?: { width: number; height: number };
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(true);

  useEffect(() => {
    const video = videoRef.current;
    if (!video || !active) return;

    // Source-qualified when a source is named. The bare path remains the
    // default programme's alias, so a caller that has no id in hand still works.
    const src = sourceId ? `/hls/${sourceId}/index.m3u8` : "/hls/index.m3u8";
    let hls: Hls | null = null;
    let retry: number | undefined;

    const start = () => {
      if (Hls.isSupported()) {
        hls = new Hls({
          // Tuned for a monitor feed: stay near the live edge and prefer
          // skipping to catching up smoothly.
          lowLatencyMode: true,
          // Load-bearing, and it was missing. hls.js gates its whole
          // catch-up controller on
          //   !lowLatencyMode || maxLiveSyncPlaybackRate === 1
          // and maxLiveSyncPlaybackRate DEFAULTS TO 1 (verified in the
          // installed 1.6.16 build), so lowLatencyMode alone returned early
          // every time and the player never nudged itself back toward the
          // edge. 1.08 is fast enough to recover a second of drift within a
          // few seconds and slow enough that nobody hears the pitch shift.
          maxLiveSyncPlaybackRate: 1.08,
          // Target latency is liveSyncDurationCount x EXT-X-TARGETDURATION.
          // At the 1s segments the server now emits, that is 2s.
          liveSyncDurationCount: 2,
          liveMaxLatencyDurationCount: 6,
          maxBufferLength: 6,
          manifestLoadingMaxRetry: 0,
          levelLoadingMaxRetry: 2,
        });
        hls.loadSource(src);
        hls.attachMedia(video);
        hls.on(Hls.Events.MANIFEST_PARSED, () => {
          void video
            .play()
            .then(() => setPlaying(true))
            .catch(() => setPlaying(false));
        });
        hls.on(Hls.Events.ERROR, (_e, data) => {
          if (!data.fatal) return;
          setPlaying(false);
          hls?.destroy();
          hls = null;
          // No playlist yet just means nobody is streaming. Keep looking.
          retry = window.setTimeout(start, 4000);
        });
      } else if (video.canPlayType("application/vnd.apple.mpegurl")) {
        // Safari plays HLS natively and does not need (or want) hls.js.
        video.src = src;
        void video
          .play()
          .then(() => setPlaying(true))
          .catch(() => setPlaying(false));
      }
    };

    start();
    return () => {
      if (retry) window.clearTimeout(retry);
      hls?.destroy();
      // CLEAR THE PICTURE, not only the player. Destroying the Hls instance
      // leaves the <video> holding its last decoded frame, so switching source
      // showed the previous programme under the new one's name until the first
      // segment of the new one arrived.
      setPlaying(false);
      // No null check: the effect returned early unless `video` was already
      // there, and it is a const, so this cannot be reached with nothing to
      // clear. load() is the part that matters -- removing the attribute alone
      // does not release the frame the element is already showing.
      video.pause();
      video.removeAttribute("src");
      video.load();
    };
  }, [active, sourceId]);

  /* max-h, because aspect-video alone grows without limit.
   *
   * The preview is 16:9 of whatever width it is given, and the dashboard
   * gives it `minmax(0,1fr)` beside a fixed 20rem column. On a 1440px window
   * that is a ~530px preview and looks right. Maximised on a 27" display the
   * main column is ~1490px, so the preview becomes ~838px TALL and pushes the
   * destination cards, the ingest stats and the publish URL below the fold --
   * on the one page whose job is showing you all of them at once. The bigger
   * the screen, the less of the dashboard you can see, which is exactly
   * backwards.
   *
   * Capping the height rather than the app's width is deliberate. This is a
   * monitoring UI: the destination grid, the meters and chat all earn extra
   * width, and a global max-width would throw two thirds of an ultrawide away
   * to fix one component. `object-contain` on the video already letterboxes
   * whatever the source aspect is, so a shorter box crops nothing.
   */
  // Geometry as a CSS ratio, only once both numbers are real: a 0 would
  // collapse the tile.
  const ratio =
    aspect && aspect.width > 0 && aspect.height > 0
      ? `${aspect.width} / ${aspect.height}`
      : undefined;

  // outputLive is undefined for a caller that does not supply telemetry, and
  // that must behave exactly as before rather than blanking every preview.
  const onAirKnown = outputLive !== undefined;
  const offAir = onAirKnown && !outputLive;
  const showPicture = playing && !offAir;
  // Something is going out, but it is not the operator's encoder.
  const standingIn =
    onAirKnown && outputLive === true && ingestLive === false && Boolean(onAir);

  return (
    <div
      className={cn(
        "relative max-h-[60vh] w-full overflow-hidden rounded-md border border-border bg-black",
        // Falls back to 16:9 only while the geometry is unknown. A measured
        // source draws in its own shape, so a vertical or 4:3 programme is not
        // letterboxed into a box it never filled.
        !ratio && "aspect-video",
        className,
      )}
      style={ratio ? { aspectRatio: ratio } : undefined}
    >
      <video
        ref={videoRef}
        className="h-full w-full object-contain"
        muted={muted}
        playsInline
        controls={false}
      />

      {/* OPAQUE, and that is the fix rather than a style choice. The parent's
          bg-black sits BEHIND the <video>, so a transparent overlay let the last
          decoded frame of a finished stream show straight through with
          "Waiting for a stream…" floating on top of it. */}
      {!showPicture && (
        <div className="absolute inset-0 flex flex-col items-center justify-center gap-2 bg-black text-muted-foreground">
          <MonitorPlay className="h-6 w-6 opacity-40" />
          <span className="text-[11px]">
            {!active
              ? "Preview is disabled in Settings"
              : offAir
                ? "Ingest offline"
                : "Waiting for a stream…"}
          </span>
          {offAir && (
            <span className="text-[10px] opacity-70">
              Start your encoder to see the preview
            </span>
          )}
        </div>
      )}

      {/* THE LABEL DOES NOT COVER THE PICTURE. With the slate or a backup on
          air, something real is being broadcast and the operator needs to see
          it -- the preview has been blind at exactly this moment. So the state
          is said in a corner, over a live image, rather than instead of it. */}
      {/* Not gated on the picture having started. "The input is gone and the
          slate is going out" is true while the tile is still buffering, and a
          label that appears only once decoding succeeds is missing during the
          seconds an operator is most likely to be looking. */}
      {standingIn && (
        <div className="absolute left-2 top-2 flex items-center gap-1.5 rounded bg-black/70 px-1.5 py-0.5 backdrop-blur-sm">
          <span className="text-[10px] font-medium uppercase tracking-wider text-warn">
            Input offline
          </span>
          <span className="text-[10px] text-muted-foreground">
            showing {onAir}
          </span>
        </div>
      )}

      {playing && (
        <div className="absolute bottom-2 right-2 flex items-center gap-1">
          <Button
            variant="secondary"
            size="icon-sm"
            onClick={() => setMuted((m) => !m)}
            aria-label={muted ? "Unmute preview" : "Mute preview"}
          >
            {muted ? <VolumeX /> : <Volume2 />}
          </Button>
        </div>
      )}
    </div>
  );
}
