package scheduler

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// updateContract rewrites the committed JSON instead of comparing against it.
//
// A flag rather than an environment variable so `go test -h` lists it, and so
// the regeneration hint in the failure message is a command somebody can paste.
var updateContract = flag.Bool("update-contract", false,
	"rewrite ui/src/lib/contract/scheduler-actions.json from the server's own list")

// contractPath is the committed list the UI checks itself against.
const contractPath = "../../ui/src/lib/contract/scheduler-actions.json"

// Every action the operator can be offered must survive Validate.
//
// THIS REPLACES A TEST THAT READ scheduler.go WITH A REGEXP, which is what #107
// is about. The old pair asserted two things by reading source text: that every
// Action constant appeared in a list restated inside the test file, and that
// each one appeared as a `<SelectItem value="...">` in AutomationPage.tsx.
// Neither ever called Validate, so both would have gone green on an action the
// server rejects, and green again on one it accepts but nothing implements.
//
// This one calls it. AllActions is the slice Validate itself ranges over, so
// the loop below walks the production list through the production check.
func TestValidateAcceptsEveryActionItOffers(t *testing.T) {
	if len(AllActions) == 0 {
		t.Fatal("AllActions is empty, so this test asserts nothing")
	}
	for _, a := range AllActions {
		// A complete one-shot: Validate checks the whole schedule, so an
		// incomplete fixture would fail for a reason that has nothing to do
		// with the action under test.
		s := Schedule{
			Name:   "nightly",
			Action: a,
			Kind:   KindOnce,
			RunAt:  time.Date(2026, 8, 9, 20, 0, 0, 0, time.UTC),
		}.Normalized()
		if err := s.Validate(); err != nil {
			t.Errorf("Validate rejected %q, which AllActions offers: %v", a, err)
		}
	}
}

// And an action that is not in the list has to be refused.
//
// The pair matters: without this, AllActions could grow to contain every string
// in the world and the test above would still pass.
func TestValidateRejectsAnActionItDoesNotOffer(t *testing.T) {
	s := Schedule{
		Name:   "nightly",
		Action: Action("pause"),
		Kind:   KindOnce,
		RunAt:  time.Date(2026, 8, 9, 20, 0, 0, 0, time.UTC),
	}.Normalized()
	if err := s.Validate(); err == nil {
		t.Fatal("Validate accepted the action \"pause\", which AllActions does not offer. " +
			"An unknown action reaching the runner takes the DESTINATION path -- Enables() " +
			"answers false for anything that is not ActionStart -- and disables every " +
			"destination in the install.")
	}
}

// Each action must route to exactly one half of the runner.
//
// TargetsPlaylist decides that, and Enables decides what gets written. The old
// guard's stated fear was a fifth action falling through to the destination
// path by accident; this asserts the routing directly instead of inferring it
// from a dropdown's source text.
func TestEveryActionRoutesToOneHalfOfTheRunner(t *testing.T) {
	playlist := map[Action]bool{ActionPlaylistStart: true, ActionPlaylistStop: true}
	for _, a := range AllActions {
		s := Schedule{Name: "x", Action: a, Kind: KindOnce}.Normalized()
		if got, want := s.TargetsPlaylist(), playlist[a]; got != want {
			t.Errorf("action %q: TargetsPlaylist()=%v, want %v. An action on the wrong "+
				"side of this predicate acts on the other half of the install.", a, got, want)
		}
	}
}

// The committed contract must match what the server offers.
//
// WHY A FILE RATHER THAN A GREP OF THE UI. The claim being guarded is
// set agreement -- the server and the operator's dropdown must offer the same
// actions -- and the old guard tested it by searching AutomationPage.tsx for a
// `<SelectItem value="...">`. That could not tell whether the component
// compiles, could not survive the dropdown being refactored to map over an
// array (its own comment says so), and was satisfied by the string appearing
// in a comment.
//
// So the two sides meet at a committed artifact instead. This test writes what
// the server offers; ui/src/lib/contract/scheduler-actions.test.ts imports the
// REAL TypeScript module the dropdown renders from and compares it to the same
// file -- a test that cannot pass on a module that does not compile. Both the
// go job and the ui job run on every pull request, so neither side can move
// without the other's gate firing.
//
// Regenerate with: go test ./internal/scheduler/ -update-contract
func TestTheCommittedContractMatchesWhatTheServerOffers(t *testing.T) {
	want, err := json.MarshalIndent(map[string]any{
		"_comment": "Generated by internal/scheduler's TestTheCommittedContractMatchesWhatTheServerOffers. " +
			"Do not edit by hand: regenerate with `go test ./internal/scheduler/ -update-contract`.",
		"actions": AllActions,
	}, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	want = append(want, '\n')

	if *updateContract {
		if err := os.MkdirAll(filepath.Dir(contractPath), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(contractPath, want, 0o644); err != nil {
			t.Fatalf("write contract: %v", err)
		}
		t.Log("contract rewritten")
		return
	}

	got, err := os.ReadFile(contractPath)
	if err != nil {
		t.Fatalf("cannot read %s: %v\nRegenerate it with: go test ./internal/scheduler/ -update-contract", contractPath, err)
	}
	if string(got) != string(want) {
		t.Errorf("%s is out of date.\n got:\n%s\nwant:\n%s\n\n"+
			"The server's actions and the committed contract disagree. Regenerate with "+
			"`go test ./internal/scheduler/ -update-contract`, and expect the UI's own test "+
			"to fail next until the dropdown offers the same set.", contractPath, got, want)
	}
}
